// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_03InveOvFFXjTYbB85ce6PE_KLUoJ7k',
    appId: '1:293380560932:web:c84cf31c7379a18c9d60b1',
    messagingSenderId: '293380560932',
    projectId: 'train-project-iot',
    authDomain: 'train-project-iot.firebaseapp.com',
    databaseURL: 'https://train-project-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-project-iot.appspot.com',
    measurementId: 'G-F2J8EYK7KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0puHovlygpakDotUKxPwAB1_9XSpebeI',
    appId: '1:293380560932:android:b72c5cfdc0e5d4759d60b1',
    messagingSenderId: '293380560932',
    projectId: 'train-project-iot',
    databaseURL: 'https://train-project-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-project-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvicsGgDA2MCQF2buySSpyfw6tx-L0mA',
    appId: '1:293380560932:ios:903d7652cd24d9209d60b1',
    messagingSenderId: '293380560932',
    projectId: 'train-project-iot',
    databaseURL: 'https://train-project-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-project-iot.appspot.com',
    iosBundleId: 'com.technion.iot.train.train',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLvicsGgDA2MCQF2buySSpyfw6tx-L0mA',
    appId: '1:293380560932:ios:43a98a46a88de9109d60b1',
    messagingSenderId: '293380560932',
    projectId: 'train-project-iot',
    databaseURL: 'https://train-project-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-project-iot.appspot.com',
    iosBundleId: 'com.technion.iot.train.train.RunnerTests',
  );
}
